# Generated by Django 3.2.18 on 2023-04-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aws_access_key',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='aws_secret_key',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
