# Generated by Django 3.2.18 on 2023-04-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_auto_20230420_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
