# Generated by Django 3.2.18 on 2023-04-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
