# Generated by Django 3.2.18 on 2023-04-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user_profile', 'verbose_name_plural': 'user_profile_group'},
        ),
    ]
